#!/usr/bin/env node
/**
 * Applies a Story Builder JSON package into pokeemerald-expansion source.
 * Generates custom text includes under data/text/story_hack/
 */
import fs from "node:fs";
import path from "node:path";

const storyJsonPath = process.argv[2] || "story-package.json";
const expansionRoot = process.argv[3] || path.join("..", "hack", "pokeemerald-expansion");

const pkg = JSON.parse(fs.readFileSync(storyJsonPath, "utf8"));
const outDir = path.join(expansionRoot, "data", "text", "story_hack");

fs.mkdirSync(outDir, { recursive: true });

const lines = [
  "/* Auto-generated by Story Builder — do not edit by hand */",
  "",
  `#ifndef GUARD_STORY_HACK_TEXT_H`,
  `#define GUARD_STORY_HACK_TEXT_H`,
  "",
  `// Hack: ${pkg.hackTitle}`,
  `// Scenes: ${pkg.scenes.length}`,
  "",
];

for (const scene of pkg.scenes) {
  const label = sanitizeLabel(scene.id);
  lines.push(`// --- ${scene.title} (${scene.map || "unknown map"}) ---`);
  for (let i = 0; i < scene.dialogue.length; i++) {
    const d = scene.dialogue[i];
    const text = escapeCString(d.line);
    lines.push(
      `static const u8 sStoryHack_${label}_Line${i + 1}[] = _("${d.speaker}: ${text}");`,
    );
  }
  lines.push("");
}

lines.push(`#endif // GUARD_STORY_HACK_TEXT_H`, "");

fs.writeFileSync(path.join(outDir, "story_hack_text.inc"), lines.join("\n"));

const manifest = {
  hackTitle: pkg.hackTitle,
  sceneCount: pkg.scenes.length,
  scenes: pkg.scenes.map((s) => ({
    id: s.id,
    map: s.map,
    vanillaEvent: s.vanillaEvent,
    lineCount: s.dialogue.length,
  })),
};

fs.writeFileSync(
  path.join(outDir, "manifest.json"),
  JSON.stringify(manifest, null, 2),
);

console.log(`Applied ${pkg.scenes.length} scenes to ${outDir}`);

function sanitizeLabel(id) {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

function escapeCString(str) {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
